### ISSUE TITLE
Proposal of porting changes - once again

### ISSUE THREAD

**Issue by it-praktyk** [semuconsulting/ansible_octoprint#11]
Hi @semuadmin,
few years ago, I opened the pull request #1 - but it was not handled by you in reasonable time, and the next closed.

Now I can try to port my changes, once again, if you will declare that you will find time to review them and merge.

The main improvement is possibility to pin the OctoPrint version (installation via pip) and many smaller as well.

**Comment by semuadmin** [comment]
Hi @it-praktyk 

Apologies for not responding to your earlier PR in a reasonable timeframe, but please appreciate that maintaining this repo is entirely voluntary and depends on my other (paid) commitments.

If you're happy to submit a further PR I will do my best to review it within the next two or three weeks, but I can give no absolute guarantee of the timeframe or that I will accept the PR once it's submitted.

**Comment by it-praktyk** [comment]
OK, so I will try to prepare a series of PR in next few days.
