### ISSUE TITLE
Skip config.yaml updates when upgrading existing OctoPrint installation

### ISSUE THREAD

**Issue by tideline3d** [semuconsulting/ansible_octoprint#6]
Thanks for creating this, I'm trying to use it to manage the OctoPrint install across multiple Pis in my print farm.   Curious if you designed this to be run repeatedly for new updates.  I would love to have a test host group running 1.5.2 and my prod group running 1.4.2 (or something similar).  

However when I change the URL and re-run the install, it appears OP generates a new salt in the config.yaml but the users.yaml password (of course) isn't re-generated with the new salt.  

Uninstall / reinstall seems to work, but I'd love to find a way to just install an OP update and not re-generate that salt every time.

Would love your thoughts as to if this is an enhancement to this role, or I need to invent another solution here (possibly just preserving the salt / users.yaml across the uninstall/reinstall cycle).

**Comment by semuadmin** [comment]
Hi. To answer your question, the role was indeed designed to be 'run repeatedly' across multiple Pi farms - that was exactly my original use case - but it does as you say effectively reset the access credentials after each fresh install. I presume what you need is the ability to update multiple servers without having to manually update the credentials each time? I see no reason why this shouldn't be possible with modifications to the config.yaml template - let me look into it and get back to you.

**Comment by semuadmin** [comment]
This might prove to be an overly-simplistic approach to the issue, but I've added a 'reset_config' flag to the octoprint install tasks. The default is 'false', but if set to 'true' it will retain any existing config.yaml, including the current access salt. Do you want to give this a go and let me know if it solves your problem?

**Comment by tideline3d** [comment]
Will do.  I spoke with some others about this and they suggested the 'firstRun: false' option in config.yaml may be of use as well.  

I will try your update out today and post an update.

**Comment by tideline3d** [comment]
@semuadmin thinking out loud here, shouldn't that setting be flipped for better readability?   reset_config = true by default and that is the current action, then reset_config=false would be for update without resetting the config.yaml?   Or keep the same booleans and rename the setting to 'retain_config'?

**Comment by semuadmin** [comment]
Subjective I guess, but if the flag is called 'reset_config' then it makes more sense to me for 'false' to signify 'don't reset the config' i.e. 'keep the existing config.yaml', and for 'true' to signify 'do reset the config' i.e. create a new config.yaml. Hopefully as long as the example is clear in the README, people will get the gist of it. But I'm very happy to rename if there's a alternative consensus.

Either way, does this flag actually solve the issue in hand?

**Comment by tideline3d** [comment]
Yep, I agree with your wording, I just was going off your comment.  I hadn't seen the README from my phone yet.

Just tested it out on a fresh RaspiOS SD.   First install with it set to true for 1.5.0 then changed to false + 1.5.2 and it upgrade fine, and I could still login.

I also tried a fresh install with reset_config = false and OctoPrint sets up a default config.yaml just fine.   So I'll probably just keep it at that for my purposes as I expect I'll the config.yaml updates separately.

**Comment by semuadmin** [comment]
Glad this sorted your issue. FYI re. config.yaml updates - my original intention in providing a templated config.yaml for new installations was to have the service stop/start commands and webcam streaming URL pre-populated, as this was often a source of some confusion for new users. I do of course acknowledge that a) Octoprint will generate its own 'blank' config.yaml on first installation anyway, and b) the template I provide only covers a small subset of the options available in the full configuration specification. 

I had considered providing a more comprehensively parameterised config.yaml template (with a more extensive range of default values) but didn't want to be constantly playing 'catch-up' with new versions. If there's a wider appetite to have this kind of functionality, more than happy to consider it.

**Comment by tideline3d** [comment]
I thought about this later and you could probably just remove the salt entry from the template and then it wouldn't overwrite when updating but the rest of the templating features would still be available.  I will give this a shot and see if that actually works.
